<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AWS_EC_WorkerService-dd03a7dd-1554-4e44-b392-645c628e603e</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWS.Logger.AspNetCore" Version="3.5.3" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.400" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.400.119" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
  </ItemGroup>
</Project>
